user/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import (RedirectView, TemplateView)
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from .views import ActivateAccount, ProviderSignUpView, ResendActivationEmail, profile


app_name = "user"

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='user:pw_reset_start',
            permanent=False)),

    url(r'^change/$',
        auth_views.PasswordChangeView.as_view(
        template_name=
            'user/password_change_form.html',
         success_url= reverse_lazy(
            'user:pw_change_done')),
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.PasswordChangeDoneView.as_view(
        template_name=
            'user/password_change_done.html'),
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
        template_name=
            'user/password_reset_form.html',
         email_template_name=
            'user/password_reset_email.txt',
         subject_template_name=
            'user/password_reset_subject.txt',
         success_url= reverse_lazy(
            'user:pw_reset_sent')),
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.PasswordResetDoneView.as_view(
        template_name=
            'user/password_reset_sent.html'),
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
        template_name=
            'user/password_reset_confirm.html',
        success_url= reverse_lazy(
            'user:pw_reset_complete')),
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(
        template_name=
            'user/password_reset_complete.html',
        extra_context=
             {'form': AuthenticationForm}),
        name='pw_reset_complete'),
]


urlpatterns = [

		url(r'^$',
        RedirectView.as_view(
            pattern_name='user:login',
            permanent=False)),
		
		url(r'^create-provider/$',
        ProviderSignUpView.as_view(),
        name='create_provider'),

        url(r'^create-provider/done/$',
        TemplateView.as_view(
        template_name=(
        'user/user_create_done.html')),
        name='create_done'),

		url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),

		url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),

		url(r'^login/$',
        LoginView.as_view(
        template_name= 'user/login.html'),
        name='login'),

		url(r'^logout/$',
        auth_views.LogoutView.as_view(
        template_name= 'user/logged_out.html',
        extra_context=
             {'form': AuthenticationForm}),
        name='logout'),

        url(r'^password/', include(password_urls)),

        url(r"^profile/$",profile,name="profile"),


]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
	{% block title %}
    Startup PVS
    {% endblock %}
	</title>
    <!-- Jquery -->
    <script src="https://sp.zalo.me/plugins/sdk.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <script src="{% static 'js/popper.min.js' %}"> </script>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/js/bootstrap4-toggle.min.js"></script>

    <!-- Custom fonts for this template -->
    <!--<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    

    <!-- Custom styles for this template -->
    <link href="{% static 'css/agency.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/pagination_result.css' %}" rel="stylesheet">
    <link href="{% static 'css/filter_form.css' %}" rel="stylesheet">
    

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color:#333;">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'search_device' %}"><img src="{% static 'img/logos/pvs-logo.png' %}" alt="pvs-logo" style="width:100px;margin-top:auto;margin-bottom:auto;"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            {% if user.is_authenticated %}
              {% if user.is_provider %}
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'import_data' %}">Upload</a>
              </li>
              {% endif %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'user:logout' %}" class="nav-link js-scoll-trigger">Log Out</a>
            </li>
            {% else %}
          
            <li class="nav-item">
              <a href="{% url 'user:login' %}" class="nav-link js-scroll-trigger">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'user:create_provider' %}">SignUp</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
    <header class="masthead">
      
    </header>
	{% block content %}
    
	{% endblock %}

    <!-- Clients -->


    <!-- Contact -->
  

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; PVS Website 2019</span>
          </div>
    
        </div>
      </div>
    </footer>

    <!-- Portfolio Modals -->


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    

    <!-- Plugin JavaScript -->
    <!--<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>-->


    <!-- Custom scripts for this template -->
    <!--<script src="{% static 'js/agency.min.js' %}"></script>-->

  </body>

</html>

templates/base_search.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
	{% block title %}
    Startup PVS
    {% endblock %}
	</title>
    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/js/bootstrap4-toggle.min.js"></script>
    <!-- Bootstrap core CSS -->
    <script src="{% static 'js/popper.min.js' %}"> </script>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <!--<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/agency.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/pagination_result.css' %}" rel="stylesheet">
    <link href="{% static 'css/filter_form.css' %}" rel="stylesheet">
  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color:#333;">
      <div class="container">
        
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            {% if user.is_authenticated %}
            {% if user.is_provider %}
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'import_data' %}">Upload</a>
              </li>
              {% endif %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'user:logout' %}" class="nav-link js-scoll-trigger">Log Out</a>
            </li>
            {% else %}
          
            <li class="nav-item">
              <a href="{% url 'user:login' %}" class="nav-link js-scroll-trigger">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'user:create_provider' %}">SignUp</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
    <header class="masthead">
      
    </header>
	{% block content %}
    
	{% endblock %}

    <!-- Clients -->


    <!-- Contact -->
  

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; PVS Website 2019</span>
          </div>
    
        </div>
      </div>
    </footer>

    <!-- Portfolio Modals -->


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/agency.min.js' %}"></script>

  </body>

</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{block.super}} - Main page
{% endblock %}

{% block content %}






{% endblock %}