user/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import (RedirectView, TemplateView)
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from .views import ActivateAccount, ProviderSignUpView, ResendActivationEmail, profile


app_name = "user"

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='user:pw_reset_start',
            permanent=False)),

    url(r'^change/$',
        auth_views.PasswordChangeView.as_view(
        template_name=
            'user/password_change_form.html',
         success_url= reverse_lazy(
            'user:pw_change_done')),
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.PasswordChangeDoneView.as_view(
        template_name=
            'user/password_change_done.html'),
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
        template_name=
            'user/password_reset_form.html',
         email_template_name=
            'user/password_reset_email.txt',
         subject_template_name=
            'user/password_reset_subject.txt',
         success_url= reverse_lazy(
            'user:pw_reset_sent')),
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.PasswordResetDoneView.as_view(
        template_name=
            'user/password_reset_sent.html'),
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
        template_name=
            'user/password_reset_confirm.html',
        success_url= reverse_lazy(
            'user:pw_reset_complete')),
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(
        template_name=
            'user/password_reset_complete.html',
        extra_context=
             {'form': AuthenticationForm}),
        name='pw_reset_complete'),
]


urlpatterns = [

		url(r'^$',
        RedirectView.as_view(
            pattern_name='user:login',
            permanent=False)),
		
		url(r'^create-provider/$',
        ProviderSignUpView.as_view(),
        name='create_provider'),

        url(r'^create-provider/done/$',
        TemplateView.as_view(
        template_name=(
        'user/user_create_done.html')),
        name='create_done'),

		url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),

		url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),

		url(r'^login/$',
        LoginView.as_view(
        template_name= 'user/login.html'),
        name='login'),

		url(r'^logout/$',
        auth_views.LogoutView.as_view(
        template_name= 'user/logged_out.html',
        extra_context=
             {'form': AuthenticationForm}),
        name='logout'),

        url(r'^password/', include(password_urls)),

        url(r"^profile/$",profile,name="profile"),


]

user/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)

# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(
            self, email, password, **kwargs):
        email = self.normalize_email(email)
        is_staff = kwargs.pop('is_staff', False)
        is_superuser = kwargs.pop(
            'is_superuser', False)
        user = self.model(
            email=email,
            is_active=True,
            is_provider=False,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(
            self, email, password=None,
            **extra_fields):
        return self._create_user(
            email, password, **extra_fields)

    def create_superuser(
            self, email, password,
            **extra_fields):
        return self._create_user(
            email, password,
            is_staff=True, is_superuser=True,
            **extra_fields)

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField("staff status",default=False,help_text='Designates whether the user can log into this admin site.')
    is_active = models.BooleanField("active",default=True,help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')
    is_provider = models.BooleanField(default=False)
    USERNAME_FIELD = "email"

    objects = UserManager()

    def __str__(self):
        if self.is_provider:
            # return self.provider.name
            return self.email
        else:
            return self.email

class Provider(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=10,unique=True)
    full_name = models.CharField(max_length=100,unique=True)
    phone = models.CharField(max_length=15,unique=True)
    url = models.URLField(max_length=200,unique=True)
    skype_name = models.CharField(max_length=50,unique=True,blank=True,null=True)
    zalo_link = models.URLField(max_length=200,unique=True,blank=True,null=True)
    slug = models.SlugField(max_length=30,unique=True)

    def __str__(self):
        return self.name

user/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth import (
    get_user, get_user_model, logout)
from django.contrib.auth.decorators import \
    login_required
from django.contrib.auth.tokens import \
    default_token_generator as token_generator
from django.contrib.messages import error, success
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.template.response import \
    TemplateResponse
from django.utils.decorators import \
    method_decorator
from django.utils.encoding import force_text
from django.utils.http import \
    urlsafe_base64_decode
from django.views.decorators.cache import \
    never_cache
from django.views.decorators.csrf import \
    csrf_protect
from django.views.decorators.debug import \
    sensitive_post_parameters
from django.views.generic import View

from .utils import MailContextViewMixin
from .forms import (
    ResendActivationEmailForm, ProviderSignUpForm, ProviderChangeForm)
from .models import Provider, User
from search_device.forms import AddDeviceForm, AddStoreForm
from search_device.models import ManageDevice, RequestQuota


# Create your views here.



class ActivateAccount(View):
    success_url = reverse_lazy('user:login')
    template_name = 'user/user_activate_failed.html'

    @method_decorator(never_cache)
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            # urlsafe_base64_decode()
            #     -> bytestring in Py3
            uid = force_text(
                urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError,
                OverflowError, User.DoesNotExist):
            user = None
        if (user is not None
                and token_generator
                .check_token(user, token)):
            user.is_active = True
            user.save()
            success(
                request,
                'User Activated! '
                'You may now login.')
            return redirect(self.success_url)
        else:
            return TemplateResponse(
                request,
                self.template_name)

class ProviderSignUpView(MailContextViewMixin, View):
    form_class = ProviderSignUpForm
    success_url = reverse_lazy(
        'user:create_done')
    template_name = 'user/user_create_provider.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form': self.form_class()})

    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters(
        'password1', 'password2'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            # not catching returned user
            bound_form.save(
                **self.get_save_kwargs(request))
            if bound_form.mail_sent:  # mail sent?
                return redirect(self.success_url)
            else:
                errs = (
                    bound_form.non_field_errors())
                for err in errs:
                    error(request, err)
                # TODO: redirect to email resend
                return redirect("user:resend_activation")
        return TemplateResponse(
            request,
            self.template_name,
            {'form': bound_form})

class ResendActivationEmail(
        MailContextViewMixin, View):
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('user:login')
    template_name = 'user/resend_activation.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form': self.form_class()})

    @method_decorator(csrf_protect)
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(
                **self.get_save_kwargs(request))
            if (user is not None
                    and not bound_form.mail_sent):
                errs = (
                    bound_form.non_field_errors())
                for err in errs:
                    error(request, err)
                if errs:
                    bound_form.errors.pop(
                        '__all__')
                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form': bound_form})
        success(
            request,
            'Activation Email Sent!')
        return redirect(self.success_url)

def profile(request):
    user = request.user
    tickets = RequestQuota.objects.all()
    # view for PVS staffs
    if user.is_staff:
        if user.is_superuser:
            roles = "Admin"
        else:
            roles = "PVS staff"
        list_device = ManageDevice.objects.filter(public=True)
        if request.method=="POST":
            form = ProviderChangeForm(request.POST,user=request.user)
            if form.is_valid():
                form.save()
                return redirect("user:profile")
        else:
            form = ProviderChangeForm()
            vendors = User.objects.filter(is_provider=True)
        return render(request,"user/profile_pvs.html",{"form":form,"roles":roles,"list_device":list_device,"vendors":vendors,"tickets":tickets})

    # view for vendor
    elif user.is_provider:
        roles = "Provider"
        list_device = ManageDevice.objects.filter(user=user)
        if request.method == "POST":
            form = ProviderChangeForm(request.POST,user=request.user)
            form_add = AddDeviceForm(request.POST,user=request.user)
            form_add_store = AddStoreForm()
            if form_add.is_valid():
                print("form_add")
                form_add.save()
                return redirect("user:profile")
            
            elif form.is_valid():
                form.save()
                print("456")
                return redirect("user:profile")

        else:
            form = ProviderChangeForm()
            form_add = AddDeviceForm(user=user)
            form_add_store = AddStoreForm()           
        return render(request,"user/profile.html",{"form":form,"form_add":form_add,"form_add_store":form_add_store,"user":user,"roles":roles,"list_device":list_device})

templates/user/logged_out.html
{% extends "base.html" %}

{% block title %}
{{block.super}} - Logged Out
{% endblock %}

{% block content %}
<div class="container" style="margin-top:190px">
	<h1 style="margin-top:180px">Login Again</h1>
	<div class="offset-by-two eight columns">
		<p>You've successfully logged out.</p>
		{% include 'user/login_form.html' with login_button='Log Back In' %}
	</div>
</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}
{{block.super}} - Login
{% endblock %}

{% block content %}
<div class="container">
	<h1 style="margin-top:190px">Login</h1>
	<div class="row ">
	<div class="col-sm-auto">
		{% include "user/login_form.html" %}
	</div>
	<div class="col col-lg-3" style="margin-top:35px">
      <ul class="task-list">
      	<li><a href="{% url 'user:create_provider' %}">
          Register New Account</a></li>
        <li><a href="{% url 'user:pw_reset_start' %}">
          Forgotten password?</a></li>
        <li><a href="{% url 'user:resend_activation' %}">
          Lost Activation E-Mail?</a></li>
      </ul>
    </div>
	</div>
</div>
{% endblock %}

templates/user/login_form.html
{% load crispy_forms_tags %}

<form
    action="{% url 'user:login' %}"
    method="post">
  {% csrf_token %}
  {{ form|crispy }}
  {% if next %}
    <input
      type="hidden"
      name="next"
      value="{{ next }}">
  {% endif %}
  <button type="submit" class="btn btn-success">
    {{ login_button|default:'Log in' }}</button>
</form>

templates/user/password_change_done.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="container" style="margin-top:120px;">
    <div class="offset-by-two eight columns">
      <p>Password successfully changed.</p>
    </div>
  </div>

{% endblock %}

templates/user/password_change_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="container" style="margin-top:140px;">
    <h1>Change Password</h1>
    <div class="offset-by-two eight columns">
      <form
          action="{% url 'user:pw_change' %}"
          method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">
          Change</button>
      </form>
    </div>
  </div>

{% endblock %}

templates/user/password_reset_complete.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} - Password Reset Successful
{% endblock %}

{% block content %}
  <div class="container">
    <div class="offset-by-two eight columns" style="margin-top:180px">
      <p>Your password has been reset.</p>
      <p>Log in below using your new password.</p>
      {% include "user/login_form.html" %}
    </div>
  </div>

{% endblock %}

templates/user/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
  <div class="container">
    <div class="offset-by-two eight columns" style="margin-top:180px">
      {% if validlink %}
        <p>Enter a new password below.</p>
        <form
            action="{{ request.path }}"
            method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button
              class="button-primary"
              type="submit">
            Save New Password</button>
        </form>
      {% else %}
        <p>This reset link is no longer valid.</p>
        <p>Please request a new reset email
          <a href="{% url 'user:pw_reset_start' %}">
            here</a>.</p>
      {% endif %}
  </div>
</div>

{% endblock %}

templates/user/password_reset_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{block.super}} - Reset Password
{% endblock %}

{% block content %}

  <div class="container">
    <div class="offset-by-two eight columns">
      <div class="center" style="margin-top:180px">
        <h1>Reset your password by email</h1>
      </div>
      <form
          action="{% url 'user:pw_reset_start' %}"
          method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">
          Send Me Reset Instructions</button>
      </form>
  </div></div>


{% endblock %}

templates/user/password_reset_sent.html
{% extends "base.html" %}

{% block title %}
{{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns" style="margin-top:180px">
      <p>Password reset email sent!</p>
      <p>Please check your inbox and spam box.</p>
    </div>
  </div>

{% endblock %}

templates/user/resend_activation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{block.super}} - Resend Activation E-Mail
{% endblock %}

{% block content %}
<div class="container">
	<h1 style="margin-top:180px">Resend your account activation email</h1>
	<div>
		<form action="{% url 'user:resend_activation' %}" method="post">
			{% csrf_token %}
			{{form|crispy}}
			<button type="submit" class="btn btn-success">Resend</button>
		</form>
			
	</div>
</div>
{% endblock %}

templates/user/user_activate_failed.html
{% extends "base.html" %}

{% block title %}
{{block.super}} - Account Activation Failed
{% endblock %}

{% block content %}
<div class="container">
	<div class="offset-by-two eight columns" style="margin-top:180px">
		<p>This activation link is no longer valid.</p>
	</div>
</div>

{% endblock %}

templates/user/user_create_done.html
{% extends "base.html" %}

{% block title %}
{{block.super}} - Account Created
{% endblock %}

{% block content %}
<div class="container">
	<div class="offset-by-two eight columns">
		<p style="margin-top:180px">Your account has been created!</p>
		<p>Please check your email for the activation link.</p>
	</div>
</div>

{% endblock %}

templates/user/user_create_provider.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{block.super}} - Create Provider Account
{% endblock %}

{% block content %}
<div class="container">
	<h1 style="margin-top:180px">Create Provider Account</h1>
	<div class="offset-by-two eight columns">
		<div class="center">
			<a href="{% url 'user:resend_activation' %}">
          Lost Activation E-Mail?</a>
		</div>
		<form action="{% url 'user:create_provider' %}" method="post">
			{% csrf_token %}
			{{form|crispy}}
			<button type="submit" class="btn btn-success">Create</button>
		</form>
			
	</div>
</div>
{% endblock %}